# Generated by Django 5.0.3 on 2024-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_title', models.CharField(max_length=200)),
                ('fp_content', models.TextField()),
                ('fp_author', models.CharField(max_length=100)),
                ('fpcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
