# Generated by Django 5.0.3 on 2024-04-01 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedbackreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackReply',
            new_name='AdminReply',
        ),
        migrations.RenameField(
            model_name='adminreply',
            old_name='reply_timestamp',
            new_name='timestamp',
        ),
    ]
