# Generated by Django 5.0.3 on 2024-04-01 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_feedbackreply_adminreply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminReply',
            new_name='FeedbackReply',
        ),
    ]
