# Generated by Django 5.0.3 on 2024-04-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_adminreply_feedbackreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='fb_type',
        ),
    ]
