# Generated by Django 5.0.3 on 2024-04-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_remove_feedback_fb_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_uname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fb_uname', to=settings.AUTH_USER_MODEL),
        ),
    ]
