# Generated by Django 5.0.3 on 2024-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Art_title',
            field=models.TextField(),
        ),
    ]
