# Generated by Django 5.0.3 on 2024-03-28 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_art_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Art_content',
            new_name='art_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Art_author',
            new_name='art_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Art_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='art_publication_date',
        ),
        migrations.AddField(
            model_name='article',
            name='art_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='art_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='art_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
