# Generated by Django 5.0.3 on 2024-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_art_content_article_art_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_author',
            field=models.CharField(max_length=20),
        ),
    ]
