# Generated by Django 5.0.3 on 2024-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_art_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='art_updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='\\static\x07rticle_images'),
        ),
    ]
