# Generated by Django 5.0.3 on 2024-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_art_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
    ]
