# Generated by Django 5.0.3 on 2024-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DESAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_name', models.CharField(max_length=100)),
                ('msg_des', models.TextField()),
            ],
        ),
    ]
